import 'dart:convert';
import 'package:shared_preferences/shared_preferences.dart';
import '../models/offer.dart';
import '../models/product.dart';
import '../models/retailer.dart';

class AppData { const AppData({required this.offers, required this.favourites, required this.basket, required this.pincode}); final List<Offer> offers; final List<Product> favourites; final List<BasketItem> basket; final String pincode; factory AppData.empty() => const AppData(offers: [], favourites: [], basket: [], pincode: ''); AppData copyWith({List<Offer>? offers, List<Product>? favourites, List<BasketItem>? basket, String? pincode}) => AppData(offers: offers ?? this.offers, favourites: favourites ?? this.favourites, basket: basket ?? this.basket, pincode: pincode ?? this.pincode); }
class LocalStore { static const _key = 'favour_app_data_v4'; Future<AppData> load() async { final prefs = await SharedPreferences.getInstance(); final raw = prefs.getString(_key); if (raw != null) { final data = Map<String, dynamic>.from(jsonDecode(raw) as Map); return AppData(offers: (data['offers'] as List).map((item) => Offer.fromJson(Map<String, dynamic>.from(item as Map))).toList(), favourites: (data['favourites'] as List).map((item) => Product.fromJson(Map<String, dynamic>.from(item as Map))).toList(), basket: (data['basket'] as List).map((item) => BasketItem.fromJson(Map<String, dynamic>.from(item as Map))).toList(), pincode: data['pincode'] as String? ?? ''); } return _migrateLegacy(prefs); }
 Future<AppData> _migrateLegacy(SharedPreferences prefs) async { final legacy = prefs.getStringList('price_records') ?? []; final offers = <Offer>[]; const names = {'Blinkit': Retailer.blinkit, 'Zepto': Retailer.zepto, 'Instamart': Retailer.swiggyInstamart, 'BB Now': Retailer.bigBasketNow, 'Flipkart Minutes': Retailer.flipkartMinutes, 'Amazon Now': Retailer.amazonNow, 'JioMart': Retailer.jioMart}; for (final text in legacy) { try { final value = Map<String, dynamic>.from(jsonDecode(text) as Map); final retailer = names['${value['retailer']}']; if (retailer != null) offers.add(Offer(product: Product(name: value['product'] as String, packSize: 1, unit: Unit.piece), retailer: retailer, price: (value['price'] as num).toDouble(), timestamp: DateTime.parse(value['time'] as String), available: true)); } catch (_) {} } return AppData(offers: offers, favourites: (prefs.getStringList('favourites') ?? []).map((name) => Product(name: name, packSize: 1, unit: Unit.piece)).toList(), basket: const [], pincode: prefs.getString('pincode') ?? ''); }
 Future<void> save(AppData data) async { final prefs = await SharedPreferences.getInstance(); await prefs.setString(_key, jsonEncode({'offers': data.offers.map((item) => item.toJson()).toList(), 'favourites': data.favourites.map((item) => item.toJson()).toList(), 'basket': data.basket.map((item) => item.toJson()).toList(), 'pincode': data.pincode})); }
}
