import 'product.dart';
import 'retailer.dart';

class Offer {
  const Offer({required this.product, required this.retailer, required this.price, required this.timestamp, required this.available, this.quantity = 1, this.deliveryFee, this.handlingFee, this.otherFee});
  final Product product; final Retailer retailer; final double price; final DateTime timestamp; final bool available; final int quantity; final double? deliveryFee; final double? handlingFee; final double? otherFee;
  double get unitPrice => price / (product.packSize * quantity * product.unit.baseFactor);
  double get knownFees => (deliveryFee ?? 0) + (handlingFee ?? 0) + (otherFee ?? 0);
  Map<String, dynamic> toJson() => {'product': product.toJson(), 'retailer': retailer.name, 'price': price, 'timestamp': timestamp.toIso8601String(), 'available': available, 'quantity': quantity, 'deliveryFee': deliveryFee, 'handlingFee': handlingFee, 'otherFee': otherFee};
  factory Offer.fromJson(Map<String, dynamic> value) => Offer(product: Product.fromJson(Map<String, dynamic>.from(value['product'] as Map)), retailer: Retailer.values.byName(value['retailer'] as String), price: (value['price'] as num).toDouble(), timestamp: DateTime.parse(value['timestamp'] as String), available: value['available'] as bool? ?? true, quantity: value['quantity'] as int? ?? 1, deliveryFee: (value['deliveryFee'] as num?)?.toDouble(), handlingFee: (value['handlingFee'] as num?)?.toDouble(), otherFee: (value['otherFee'] as num?)?.toDouble());
}
class BasketItem { const BasketItem({required this.product, this.quantity = 1}); final Product product; final int quantity; Map<String, dynamic> toJson() => {'product': product.toJson(), 'quantity': quantity}; factory BasketItem.fromJson(Map<String, dynamic> value) => BasketItem(product: Product.fromJson(Map<String, dynamic>.from(value['product'] as Map)), quantity: value['quantity'] as int? ?? 1); }
class RetailerBasketTotal { const RetailerBasketTotal(this.retailer, this.total); final Retailer retailer; final double total; }
class SmartBasket { const SmartBasket({required this.splitTotal, required this.oneRetailer, required this.hasCompletePrices}); final double splitTotal; final RetailerBasketTotal? oneRetailer; final bool hasCompletePrices; bool get isSplitCheaper => oneRetailer != null && splitTotal < oneRetailer!.total; static SmartBasket calculate(List<BasketItem> basket, List<Offer> offers) { if (basket.isEmpty) return const SmartBasket(splitTotal: 0, oneRetailer: null, hasCompletePrices: false); Offer? latest(Product product, Retailer retailer) { final matches = offers.where((offer) => offer.product.id == product.id && offer.retailer == retailer && offer.available).toList()..sort((a, b) => b.timestamp.compareTo(a.timestamp)); return matches.isEmpty ? null : matches.first; } var split = 0.0; for (final item in basket) { final choices = Retailer.values.map((retailer) => latest(item.product, retailer)).whereType<Offer>().toList(); if (choices.isEmpty) return const SmartBasket(splitTotal: 0, oneRetailer: null, hasCompletePrices: false); choices.sort((a, b) => a.price.compareTo(b.price)); split += choices.first.price * item.quantity; } final totals = <RetailerBasketTotal>[]; for (final retailer in Retailer.values) { var total = 0.0; var complete = true; for (final item in basket) { final offer = latest(item.product, retailer); if (offer == null) { complete = false; break; } total += offer.price * item.quantity; } if (complete) totals.add(RetailerBasketTotal(retailer, total)); } totals.sort((a, b) => a.total.compareTo(b.total)); return SmartBasket(splitTotal: split, oneRetailer: totals.isEmpty ? null : totals.first, hasCompletePrices: true); } }
