import 'package:flutter/material.dart';
import '../models/product.dart';

class SearchScreen extends StatefulWidget { const SearchScreen({super.key, this.initialQuery}); final String? initialQuery; @override State<SearchScreen> createState() => _SearchScreenState(); }
class _SearchScreenState extends State<SearchScreen> {
  late final TextEditingController _name = TextEditingController(text: widget.initialQuery ?? '');
  final _brand = TextEditingController(); final _pack = TextEditingController(text: '1'); Unit _unit = Unit.piece;
  @override void dispose() { _name.dispose(); _brand.dispose(); _pack.dispose(); super.dispose(); }
  void _continue() { final size = double.tryParse(_pack.text.trim()); if (_name.text.trim().isEmpty || size == null || size <= 0) { ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Enter a product name and valid pack size.'))); return; } Navigator.pop(context, Product(name: _name.text.trim(), brand: _brand.text.trim(), packSize: size, unit: _unit)); }
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Search product')), body: SafeArea(child: ListView(padding: const EdgeInsets.all(20), children: [Text('What are you comparing?', style: Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight: FontWeight.w800)), const SizedBox(height: 8), const Text('Describe the exact pack. Favour uses it to calculate a fair unit price.'), const SizedBox(height: 24), TextField(controller: _name, autofocus: true, textInputAction: TextInputAction.next, decoration: const InputDecoration(labelText: 'Product name', hintText: 'e.g. Taaza Milk')), const SizedBox(height: 12), TextField(controller: _brand, textInputAction: TextInputAction.next, decoration: const InputDecoration(labelText: 'Brand (optional)', hintText: 'e.g. Amul')), const SizedBox(height: 12), Row(children: [Expanded(child: TextField(controller: _pack, keyboardType: const TextInputType.numberWithOptions(decimal: true), decoration: const InputDecoration(labelText: 'Pack size'))), const SizedBox(width: 12), Expanded(child: DropdownButtonFormField<Unit>(value: _unit, decoration: const InputDecoration(labelText: 'Unit'), items: Unit.values.map((unit) => DropdownMenuItem(value: unit, child: Text(unit.label))).toList(), onChanged: (unit) => setState(() => _unit = unit!)))]), const SizedBox(height: 24), FilledButton.icon(onPressed: _continue, icon: const Icon(Icons.compare_arrows), label: const Text('See comparison'))])));
}
