import 'package:flutter/material.dart';
import '../main.dart';
import '../models/product.dart';
import '../services/product_parser.dart';
import 'comparison_results_screen.dart';

class SearchScreen extends StatefulWidget { const SearchScreen({super.key, required this.controller}); final FavourController controller; @override State<SearchScreen> createState() => _SearchScreenState(); }
class _SearchScreenState extends State<SearchScreen> { final query = TextEditingController(); @override void dispose() { query.dispose(); super.dispose(); } void _search() { if (query.text.trim().isEmpty) return; final product = ProductParser.parse(query.text).product; Navigator.push(context, MaterialPageRoute(builder: (_) => ComparisonResultsScreen(controller: widget.controller, product: product))); }
 @override Widget build(BuildContext context) => ListView(padding: const EdgeInsets.all(20), children: [Text('Favour', style: Theme.of(context).textTheme.displaySmall?.copyWith(fontWeight: FontWeight.w800)), const Text('Your personal grocery price assistant'), const SizedBox(height: 28), TextField(controller: query, textInputAction: TextInputAction.search, onSubmitted: (_) => _search(), decoration: InputDecoration(hintText: 'Amul Taaza Milk 1L', prefixIcon: const Icon(Icons.search), suffixIcon: IconButton(icon: const Icon(Icons.arrow_forward), onPressed: _search))), const SizedBox(height: 20), Card(color: Theme.of(context).colorScheme.primaryContainer, child: const Padding(padding: EdgeInsets.all(16), child: Text('Favour only shows authorised live offers when an authorised source is connected. Otherwise, record a price or import a retailer screenshot for confirmation.'))), const SizedBox(height: 24), Text('How it works', style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.bold)), const ListTile(leading: Icon(Icons.tune), title: Text('1. Confirm the parsed product and pack')), const ListTile(leading: Icon(Icons.storefront), title: Text('2. Check retailers or import a screenshot')), const ListTile(leading: Icon(Icons.savings_outlined), title: Text('3. Compare normalized recorded prices'))]); }
